- hosts: localhost
  connection: local
  become: true

#  pre_tasks:
#    - name: update repositories
#      apt:
#        update_cache: yes
#        force_apt_get: yes
#      changed_when: False

  tasks:
    - include_tasks: configuration/users.yaml
    - include_tasks: tasks/cron.yaml
    - include_tasks: tasks/update.yaml
    - include_tasks: configuration/ufw.yaml
    - include_tasks: configuration/initial_config.yaml