- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Collector Configuration"
    minute: "10"
    job: "sudo ansible-pull -o -U https://github.com/unsinc/uns-collector.git >/dev/null 2>&1 | logger -t Collector Configuration Validation"
