- name: Update the APT repository
  apt:
    update_cache: yes
    force_apt_get: yes
  changed_when: False

- name: Initial Collector Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools
     
- name: Expand the ubuntu-lb to all the available space
  lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: 100%FREE
  ignore_errors: true

- name: Extend the filesystem
  filesystem:
    fstype: ext4
    dev: "/dev/mapper/{{vg_name}}-{{lv_name}}"
    resizefs: true
  ignore_errors: true