- name: Update the APT repository
  apt:
    update_cache: yes
    force_apt_get: yes
  changed_when: False

- name: Initial Collector Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools
      - lm-sensors
     
- name: Expand the ubuntu-lv to all the available space
  shell: "sudo lvextend -l +100%FREE /dev/ubuntu-vg/ubuntu-lv"
  ignore_errors: true

- name: Resize the file system to use all the available space
  shell: "sudo resize2fs /dev/ubuntu-vg/ubuntu-lv"
  ignore_errors: true